Repository wxt9861/esxi_stats, pull requests merged in 2019-09, with the labels that each got.

#9 update button-card-example
  examples/button-card-example.yaml
Labels: bug, documentation

#10 License Monitoring/Snapshot Service Calls
  README.md
  custom_components/esxi_stats/.translations/en.json
  custom_components/esxi_stats/__init__.py
  custom_components/esxi_stats/config_flow.py
  custom_components/esxi_stats/const.py
  custom_components/esxi_stats/esxi.py
  custom_components/esxi_stats/sensor.py
  custom_components/esxi_stats/services.yaml
  hacs.json
  info.md
Labels: documentation, enhancement

#12 Maintenance/Bugfix Update
  custom_components/esxi_stats/__init__.py
  custom_components/esxi_stats/const.py
  custom_components/esxi_stats/esxi.py
  custom_components/esxi_stats/manifest.json
  requirements.txt
Labels: bug, enhancement
